name: Destroy EC2 Instance

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Triggers on push to the main branch

jobs:
  destroy-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.3  # Specify the version of Terraform to use

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Change to your preferred AWS region

    - name: Initialize Terraform
      run: terraform init
