name: Destroy EC2 Instance

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main  
jobs:
  destroy-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.3  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-cli@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1 

    - name: Initialize Terraform
      run: terraform init

    - name: Destroy EC2 Instance
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
